---
apiVersion: v1
kind: Namespace
metadata:
  name: jump-the-queue
  labels:
    name: jtq-jump-the-queue
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jump-the-queue-frontend
  namespace: jump-the-queue
  labels:
    app: jump-the-queue-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jump-the-queue-frontend
  template:
    metadata:
      labels:
        app: jump-the-queue-frontend
    spec:
      containers:
      - name: jump-the-queue-frontend
        image: jump-the-queue-frontend:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "0.5"
            memory: "512Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jump-the-queue-backend
  namespace: jump-the-queue
  labels:
    app: jump-the-queue-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jump-the-queue-backend
  template:
    metadata:
      labels:
        app: jump-the-queue-backend
    spec:
      containers:
      - name: jump-the-queue-backend
        image: jump-the-queue-backend:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "0.5"
            memory: "256Mi"
          requests:
            cpu: "0.2"
            memory: "128Mi"
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: jump-the-queue-backend-autoscaler
  namespace: jump-the-queue
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: jump-the-queue-backend
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 50
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jump-the-queue-reverse-proxy
  namespace: jump-the-queue
  labels:
    app: jump-the-queue-reverse-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jump-the-queue-reverse-proxy
  template:
    metadata:
      labels:
        app: jump-the-queue-reverse-proxy
    spec:
      containers:
      - name: jump-the-queue-reverse-proxy
        image: jump-the-queue-reverse-proxy:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "0.5"
            memory: "256Mi"
          requests:
            cpu: "0.2"
            memory: "128Mi"
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: jump-the-queue-reverse-proxy-autoscaler
  namespace: jump-the-queue
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: jump-the-queue-reverse-proxy
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 50
---
apiVersion: v1
kind: Service
metadata:
  name: jump-the-queue-reverse-proxy-svc
  namespace: jump-the-queue
  labels:
    app: jump-the-queue-reverse-proxy
spec:
  type: NodePort
  selector:
    app: jump-the-queue-reverse-proxy
  ports:
    - name: front
      protocol: TCP
      port: 80
      nodePort: 31000
    - name: back
      protocol: TCP
      port: 8081
      targetPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: jump-the-queue-frontend
  namespace: jump-the-queue
  labels:
    app: jump-the-queue-frontend
spec:
  type: ClusterIP
  selector:
    app: jump-the-queue-frontend
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: jump-the-queue-backend
  namespace: jump-the-queue
  labels:
    app: jump-the-queue-backend
spec:
  type: ClusterIP
  selector:
    app: jump-the-queue-backend
  ports:
    - protocol: TCP
      port: 8081